name: Unified CI/CD Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # allows to trigger builds manually

concurrency:
  group: ${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  avoid-redundancy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous running jobs
        uses: styfle/cancel-workflow-action
        with:
          access_token: ${{ github.token }}

  build-and-deploy:
    # Setup node and pnpm
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # Cache pnpm store
      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build the project
      - name: Build the project
        run: pnpm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        if: github.repository == 'Pool-Escrow/PWA' && (github.ref == 'refs/heads/main' || github.event_name == 'pull_request')
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
          working-directory: './' # Specify if your project directory isn't the root
